os: windows

language: shell

before_install:
  - choco install python3 --version 3.6.7
  - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"

install:
  - python -m pip install -r requirements.txt
  - python -m pip install tox-travis

script:
  - tox -e pep8
  - tox -e isort
  # can't run actual unit tests on Travis
  # https://travis-ci.org/AndreMiras/pycaw/builds/472124432
  # _ctypes.COMError: (-2147023174, 'The RPC server is unavailable.', (None, None, None, 0, None))
  # - tox -e py36
