name: Tests

on: [push]

jobs:
  linter:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - run: pip install tox
      - run: tox -e pep8
      - run: tox -e isort
  test:
    runs-on: windows-2019
    strategy:
      matrix:
        python: [3.6]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install tox
      # # can't run actual unit tests in GitHub Actions
      # https://github.com/AndreMiras/pycaw/runs/6049929435
      # _ctypes.COMError: (-2147023728, 'Element not found.', (None, None, None, 0, None))
      # - run: tox -e py
